// Generated by CoffeeScript 1.9.3
var AdjacentCellsCalculator, Tuple;

Tuple = require('../models/Tuple');

AdjacentCellsCalculator = (function() {
  function AdjacentCellsCalculator() {}

  AdjacentCellsCalculator.getAdjacent = function(solutionGrid, x, y) {
    var cells, i, j, k, l, len, len1, ref, ref1, tuple;
    cells = [];
    ref = [x - 1, x, x + 1];
    for (k = 0, len = ref.length; k < len; k++) {
      i = ref[k];
      ref1 = [y - 1, y, y + 1];
      for (l = 0, len1 = ref1.length; l < len1; l++) {
        j = ref1[l];
        if (!(i === x && j === y)) {
          tuple = this.validLocation(solutionGrid, i, j);
          if (tuple !== null) {
            cells.push(tuple);
          }
        }
      }
    }
    return cells;
  };

  AdjacentCellsCalculator.validLocation = function(solutionGrid, x, y) {
    if (this.isValidIndex(solutionGrid(x, y))) {
      if (this.isEmpty(solutionGrid, x, y)) {
        return new Tuple(x, y);
      }
    }
    return null;
  };

  AdjacentCellsCalculator.isValidIndex = function(solutionGrid, x, y) {
    return x < solutionGrid.length && x >= 0 && y < solutionGrid.length && y >= 0;
  };

  AdjacentCellsCalculator.isEmpty = function(solutionGrid, x, y) {
    return solutionGrid[y][x].value === ' ';
  };

  return AdjacentCellsCalculator;

})();

module.exports = AdjacentCellsCalculator;
