// Generated by CoffeeScript 1.9.3
var $, BoardSolvedService;

$ = require('jquery');

BoardSolvedService = (function() {
  function BoardSolvedService() {}

  BoardSolvedService.prototype.isBoardCleared = function(boardBottomRow) {
    var i, len, value;
    for (i = 0, len = boardBottomRow.length; i < len; i++) {
      value = boardBottomRow[i];
      if (value !== ' ') {
        return false;
      }
    }
    return true;
  };

  BoardSolvedService.prototype.newGameBoard = function() {
    return $('#new-game-button').trigger('click');
  };

  return BoardSolvedService;

})();

module.exports = BoardSolvedService;
