// Generated by CoffeeScript 1.9.3
var $, BoardSolvedService;

$ = require('jquery');

BoardSolvedService = (function() {
  function BoardSolvedService(board) {
    this.board = board;
  }

  BoardSolvedService.prototype.isBoardCleared = function(boardBottomRow) {
    var i, len, value;
    console.log(boardBottomRow);
    for (i = 0, len = boardBottomRow.length; i < len; i++) {
      value = boardBottomRow[i];
      if (value !== ' ') {
        return false;
      }
    }
    return true;
  };

  BoardSolvedService.prototype.newGameBoard = function(board) {
    this.board = board;
  };

  return BoardSolvedService;

})();

module.exports = BoardSolvedService;
