// Generated by CoffeeScript 1.9.3
var ExpressionGenerator;

ExpressionGenerator = (function() {
  function ExpressionGenerator() {}

  ExpressionGenerator.prototype.randInclusive = function(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  ExpressionGenerator.prototype.genRandomDigit = function(min, max) {
    return this.randInclusive(min, max).toString();
  };

  ExpressionGenerator.prototype.genRandomOperator = function() {
    switch (this.randInclusive(0, 2)) {
      case 0:
        return "+";
      case 1:
        return "-";
      case 2:
        return "*";
      default:
        return "?";
    }
  };

  ExpressionGenerator.prototype.generate = function(length) {
    var digit, expression;
    expression = this.genRandomDigit(1, 9);
    digit = true;
    length--;
    while (length > 0) {
      if (digit) {
        if ((this.randInclusive(0, 9)) < 2) {
          expression += this.genRandomDigit(0, 9);
          length--;
        }
        if (length >= 2) {
          expression += this.genRandomOperator();
          length--;
          digit = false;
        } else {
          return expression;
        }
      } else {
        expression += this.genRandomDigit(1, 9);
        length--;
        digit = true;
      }
    }
    return expression;
  };

  return ExpressionGenerator;

})();

module.exports = ExpressionGenerator;
