// Generated by CoffeeScript 1.9.3
var $, HowToPlay;

$ = require('jquery');

HowToPlay = (function() {
  function HowToPlay() {}

  HowToPlay.createHowToPlay = function(isMobile) {
    if (isMobile().any() != null) {
      return $('#how-to-play').append('<b>How To Play:</b> Solve the puzzle by clearing the board. Click adjacent tiles to create an equation, and if it equals an answer, the tiles disappear!');
    } else {
      return $('#how-to-play').append('<b>How To Play:</b> Solve the puzzle by clearing the board. Drag your mouse across the tiles to create an equation, and if it equals an answer, the tiles disappear!');
    }
  };

  return HowToPlay;

})();

module.exports = HowToPlay;
