// Generated by CoffeeScript 1.9.3
var GameGrid, LastInColumn;

GameGrid = require("../models/GameGrid");

LastInColumn = (function() {
  function LastInColumn() {}

  LastInColumn.prototype.isLastAndBlocking = function(grid) {
    var col, colCount, count, i, index, j, k, ref, ref1, ref2, row;
    colCount = [];
    for (col = i = 0, ref = grid.length - 1; 0 <= ref ? i <= ref : i >= ref; col = 0 <= ref ? ++i : --i) {
      count = 0;
      for (row = j = 0, ref1 = grid.length - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; row = 0 <= ref1 ? ++j : --j) {
        if (grid[row][col] === null) {
          count += 1;
        }
      }
      colCount.push(count);
    }
    for (index = k = 1, ref2 = colCount.length - 2; 1 <= ref2 ? k <= ref2 : k >= ref2; index = 1 <= ref2 ? ++k : --k) {
      if (colCount[index] === 1 && colCount[index - 1] > 0 && colCount[index + 1] > 0) {
        return true;
      }
    }
    return false;
  };

  return LastInColumn;

})();

module.exports = LastInColumn;
