// Generated by CoffeeScript 1.9.3
var GameGrid, LastInColumn;

GameGrid = require("../models/GameGrid");

LastInColumn = (function() {
  function LastInColumn() {}

  LastInColumn.prototype.isLastAndBlocking = function(grid, x, y) {
    var col, colCount, count, i, j, len, ref, ref1, row;
    if (x - 1 < 0 || x + 1 >= grid.dimension) {
      return false;
    }
    colCount = [];
    ref = [x - 1, x, x + 1];
    for (i = 0, len = ref.length; i < len; i++) {
      col = ref[i];
      count = 0;
      for (row = j = 0, ref1 = grid.dimension; 0 <= ref1 ? j <= ref1 : j >= ref1; row = 0 <= ref1 ? ++j : --j) {
        if (grid[row][col] === null) {
          count += 1;
        }
      }
      colCount.push(count);
    }
    if (colCount[1] === 1 && colCount[0] > 0 && colCount[2] > 0) {
      return true;
    }
    return false;
  };

  return LastInColumn;

})();

module.exports = LastInColumn;
