// Generated by CoffeeScript 1.9.3
var $, ResetButton;

$ = require('jquery');

ResetButton = (function() {
  function ResetButton(clickHandler) {
    this.clickHandler = clickHandler;
  }

  ResetButton.prototype.bindClick = function() {
    if (this.clickHandler == null) {
      return;
    }
    return $('#reset-button').click((function(_this) {
      return function(e) {
        return console.log("cliked reset button");
      };
    })(this));
  };

  return ResetButton;

})();

module.exports = ResetButton;
