// Generated by CoffeeScript 1.9.3
var $, ResetButton;

$ = require('jquery');

ResetButton = (function() {
  function ResetButton() {}

  ResetButton.bindClick = function(board) {
    return $('#reset-button').click((function(_this) {
      return function(e) {
        return board.resetBoard();
      };
    })(this));
  };

  ResetButton.unbindClick = function() {
    $('#reset-button').unbind('click');
    return ga('send', 'event', 'board', 'reset');
  };

  return ResetButton;

})();

module.exports = ResetButton;
