// Generated by CoffeeScript 1.9.3
var $, RunningSum;

$ = require('jquery');

RunningSum = (function() {
  function RunningSum() {}

  RunningSum.tilesEmptyString = 'Try to get all the tiles off the board!';

  RunningSum.solutionOperatorString = 'Solution must include an operator';

  RunningSum.invalidString = 'Invalid Expression';

  RunningSum.emptyString = '';

  RunningSum.display = function(solution, value) {
    var expression;
    if ($('#running-sum').html() !== this.tilesEmptyString) {
      if (this.isSpecialString(solution)) {
        expression = solution;
      } else if (isNaN(value)) {
        expression = this.invalidString;
      } else if (this.isCompleteExpression(solution)) {
        expression = (this.addParens(solution)) + '=' + value;
      } else {
        expression = solution;
      }
      return $('#running-sum').html(this.format(expression));
    }
  };

  RunningSum.isSpecialString = function(solution) {
    var strings;
    strings = [this.emptyString, this.tilesEmptyString, this.solutionOperatorString];
    return strings.indexOf(solution) !== -1;
  };

  RunningSum.isCompleteExpression = function(solution) {
    return solution.search(/-?\d+[-+\*]\d+/g) === 0;
  };

  RunningSum.addParens = function(solution) {
    var char, first, index, lastOpIndex;
    if (solution.length < 3) {
      return solution;
    }
    lastOpIndex = solution.search(/\d[-+\*]/g) + 1;
    index = lastOpIndex;
    while (index < solution.length) {
      char = solution[index];
      if (lastOpIndex < index && (char === '+' || char === '-' || char === '*')) {
        first = '(' + (solution.substring(0, index)) + ')';
        lastOpIndex = first.length;
        solution = first + (solution.substring(index));
      }
      index++;
    }
    return solution;
  };

  RunningSum.format = function(input) {
    return input.replace(/\*/g, ' &times; ').replace(/\+/g, ' + ').replace(/(\d+|\))-/g, '$1 - ').replace(/\=/g, ' = ');
  };

  RunningSum.empty = function() {
    return $('#running-sum').html('');
  };

  return RunningSum;

})();

module.exports = RunningSum;
