// Generated by CoffeeScript 1.9.3
var $, RunningSum;

$ = require('jquery');

RunningSum = (function() {
  function RunningSum() {}

  RunningSum.display = function(solution, value) {
    var expression;
    if (solution === '') {
      expression = '';
    } else if (isNaN(value)) {
      expression = 'Invalid Expression';
    } else if (this.isCompleteExpression(solution)) {
      expression = (this.addParens(solution)) + '=' + value;
    } else {
      expression = solution;
    }
    return $('#running-sum').html(this.format(expression));
  };

  RunningSum.isCompleteExpression = function(solution) {
    var char, i, index, len;
    for (index = i = 0, len = solution.length; i < len; index = ++i) {
      char = solution[index];
      if (char === '+' || char === '-' || char === '*') {
        return index < solution.length - 1 && '0' <= solution[index + 1] && solution[index + 1] <= '9';
      }
    }
    return false;
  };

  RunningSum.addParens = function(solution) {
    var char, first, index, lastOpIndex;
    if (solution.length < 3) {
      return solution;
    }
    lastOpIndex = -1;
    index = 2;
    while (index < solution.length) {
      char = solution[index];
      if (lastOpIndex < index && (char === '+' || char === '-' || char === '*')) {
        first = '(' + (solution.substring(0, index)) + ')';
        lastOpIndex = first.length;
        solution = first + (solution.substring(index));
      }
      index++;
    }
    return solution;
  };

  RunningSum.format = function(input) {
    return input.replace(/\*/g, " x ").replace(/\+/g, " + ").replace(/\-/g, " - ").replace(/\=/g, " = ");
  };

  return RunningSum;

})();

module.exports = RunningSum;
