// Generated by CoffeeScript 1.9.3
var RunningSum;

RunningSum = (function() {
  function RunningSum() {}

  RunningSum.display = function(solution, value) {
    if (isNaN(value)) {
      return console.log('invalid');
    } else if (this.isCompleteExpression(solution)) {
      return console.log(this.format(solution), '=', value);
    } else {
      return console.log(solution);
    }
  };

  RunningSum.isCompleteExpression = function(solution) {
    var char, i, index, len;
    for (index = i = 0, len = solution.length; i < len; index = ++i) {
      char = solution[index];
      if (char === '+' || char === '-' || char === '*') {
        return index < solution.length - 1 && '0' <= solution[index + 1] && solution[index + 1] <= '9';
      }
    }
    return false;
  };

  RunningSum.format = function(solution) {
    var char, first, index, lastOpIndex;
    lastOpIndex = -1;
    index = 0;
    while (index < solution.length) {
      char = solution[index];
      if (3 <= index && lastOpIndex < index && (char === '+' || char === '-' || char === '*')) {
        first = '(' + (solution.substring(0, index)) + ')';
        lastOpIndex = first.length;
        solution = first + (solution.substring(index));
      }
      index++;
    }
    return solution;
  };

  return RunningSum;

})();

module.exports = RunningSum;
