// Generated by CoffeeScript 1.9.3
var InputSolver, SolutionService,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

InputSolver = require('./InputSolver');

SolutionService = (function() {
  function SolutionService(board, goals) {
    this.board = board;
    this.goals = goals;
    console.log('HELLO!!!');
    console.log(this.goals);
  }

  SolutionService.prototype.isSolution = function(clickedCells) {
    var cell, i, len, ref, solution;
    if (!((clickedCells != null) && clickedCells.length > 0)) {
      return false;
    }
    solution = '';
    for (i = 0, len = clickedCells.length; i < len; i++) {
      cell = clickedCells[i];
      solution += this.board.boardValues[cell.row][cell.col];
    }
    console.log(solution, this.goals);
    return ref = InputSolver.compute(solution), indexOf.call(this.goals, ref) >= 0;
  };

  return SolutionService;

})();

module.exports = SolutionService;
