// Generated by CoffeeScript 1.9.3
var InputSolver, SolutionService,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

InputSolver = require('./InputSolver');

SolutionService = (function() {
  function SolutionService(board, goals) {
    var g, i, len;
    this.board = board;
    this.goals = [];
    for (i = 0, len = goals.length; i < len; i++) {
      g = goals[i];
      this.goals.push(g);
    }
  }

  SolutionService.prototype.isSolution = function(clickedCells) {
    var cell, i, len, soln, solution;
    if (!((clickedCells != null) && clickedCells.length > 0)) {
      return false;
    }
    solution = '';
    for (i = 0, len = clickedCells.length; i < len; i++) {
      cell = clickedCells[i];
      solution += this.board.boardValues[cell.row][cell.col];
    }
    soln = InputSolver.compute(solution);
    console.log(indexOf.call(this.goals, soln) >= 0, solution.length);
    if (!(indexOf.call(this.goals, soln) >= 0 && solution.length >= 3)) {
      return false;
    }
    this.goals.splice(this.goals.indexOf(soln), 1);
    return true;
  };

  return SolutionService;

})();

module.exports = SolutionService;
