// Generated by CoffeeScript 1.9.3
var $, TouchHandler, Tuple,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

$ = require('jquery-mobile');

Tuple = require('../models/Tuple');

TouchHandler = (function() {
  function TouchHandler(board, two, solutionService, goalContainer, clicked) {
    var cell, i, j, len, len1, ref, row;
    this.board = board;
    this.solutionService = solutionService;
    this.goalContainer = goalContainer;
    this.clicked = clicked != null ? clicked : [];
    this.mouseIsDown = false;
    if (this.board.cells == null) {
      return;
    }
    ref = this.board.cells;
    for (i = 0, len = ref.length; i < len; i++) {
      row = ref[i];
      if (row.length === 0) {
        break;
      }
      for (j = 0, len1 = row.length; j < len1; j++) {
        cell = row[j];
        if (cell.isSelected) {
          this.addToClicked(cell);
        }
      }
    }
  }

  TouchHandler.prototype.bindDefaultClick = function() {
    console.log($);
    $('body').tap((function(_this) {
      return function(e) {
        e.preventDefault();
        _this.resetClicked();
        return console.log('mouseClick');
      };
    })(this));
    return this;
  };

  TouchHandler.prototype.bindDefaultMousedown = function() {
    $('body').vmousedown((function(_this) {
      return function(e) {
        e.preventDefault();
        return _this.mouseIsDown = true;
      };
    })(this));
    return this;
  };

  TouchHandler.prototype.bindDefaultMouseup = function() {
    $('body').vmouseup((function(_this) {
      return function(e) {
        e.preventDefault();
        _this.mouseIsDown = false;
        return _this.resetClicked();
      };
    })(this));
    return this;
  };

  TouchHandler.prototype.bindClickTo = function(cells) {
    var cell, i, j, len, len1, row;
    if (cells.bindClick != null) {
      cells.bindClick();
      return;
    }
    for (i = 0, len = cells.length; i < len; i++) {
      row = cells[i];
      if (row.bindClick != null) {
        row.bindClick();
        return;
      }
      for (j = 0, len1 = row.length; j < len1; j++) {
        cell = row[j];
        if (cell.bindClick != null) {
          cell.bindClick();
        } else {
          console.log('WARN: object not 2D arrays or simpler or no BindClick method');
        }
      }
    }
  };

  TouchHandler.prototype.bindMouseenterTo = function(cells) {
    var cell, i, j, len, len1, row;
    if (cells.bindMouseenter != null) {
      cells.bindMouseenter();
      return;
    }
    for (i = 0, len = cells.length; i < len; i++) {
      row = cells[i];
      if (row.bindMouseenter != null) {
        row.bindMouseenter();
        return;
      }
      for (j = 0, len1 = row.length; j < len1; j++) {
        cell = row[j];
        if (cell.bindMouseenter != null) {
          cell.bindMouseenter();
        } else {
          console.log('WARN: object not 2D arrays or simpler or no bindMouseenter method');
        }
      }
    }
  };

  TouchHandler.prototype.bindMouseupTo = function(cells) {
    var cell, i, j, len, len1, row;
    if (cells.bindMouseup != null) {
      cells.bindMouseup();
      return;
    }
    for (i = 0, len = cells.length; i < len; i++) {
      row = cells[i];
      if (row.bindMouseup != null) {
        row.bindMouseup();
        return;
      }
      for (j = 0, len1 = row.length; j < len1; j++) {
        cell = row[j];
        if (cell.bindMouseup != null) {
          cell.bindMouseup();
        } else {
          console.log('WARN: object not 2D arrays or simpler or no bindMouseup method');
        }
      }
    }
  };

  TouchHandler.prototype.bindMousedownTo = function(cells) {
    var cell, i, j, len, len1, row;
    if (cells.bindMousedown != null) {
      cells.bindMousedown();
      return;
    }
    for (i = 0, len = cells.length; i < len; i++) {
      row = cells[i];
      if (row.bindMousedown != null) {
        row.bindMousedown();
        return;
      }
      for (j = 0, len1 = row.length; j < len1; j++) {
        cell = row[j];
        if (cell.bindMousedown != null) {
          cell.bindMousedown();
        } else {
          console.log('WARN: object not 2D arrays or simpler or no bindMousedown method');
        }
      }
    }
  };

  TouchHandler.prototype.tuplesClicked = function() {
    var cell, i, len, ref, tuples;
    tuples = [];
    ref = this.clicked;
    for (i = 0, len = ref.length; i < len; i++) {
      cell = ref[i];
      tuples.push(new Tuple(cell.col, cell.row));
    }
    return tuples;
  };

  TouchHandler.prototype.addToClicked = function(cell) {
    if (cell.isDeleted) {
      return;
    }
    return this.clicked.push(cell);
  };

  TouchHandler.prototype.removeFromClicked = function() {
    return this.clicked.pop();
  };

  TouchHandler.prototype.resetClicked = function() {
    var cell, i, ref, results;
    ref = this.clicked;
    results = [];
    for (i = ref.length - 1; i >= 0; i += -1) {
      cell = ref[i];
      results.push(this.unclickCell(cell));
    }
    return results;
  };

  TouchHandler.prototype.lastClicked = function() {
    return this.clicked[this.clicked.length - 1];
  };

  TouchHandler.prototype.checkSolution = function() {
    if (!this.solutionService.isSolution(this.clicked)) {
      return false;
    }
    this.goalContainer.deleteGoal(this.solutionService.valueIndex);
    this.board.deleteCells(this.tuplesClicked());
    this.clicked = [];
    return true;
  };

  TouchHandler.prototype.clickCell = function(cell) {
    var ref;
    if (this.clicked.length === 0 || this.areAdjacent(cell, this.lastClicked())) {
      if (ref = this.cell, indexOf.call(this.clicked, ref) < 0) {
        cell.select();
        return this.addToClicked(cell);
      }
    } else {
      this.resetClicked();
      return this.clickCell(cell);
    }
  };

  TouchHandler.prototype.areAdjacent = function(cell, otherCell) {
    return Math.abs(cell.row - otherCell.row) <= 1 && Math.abs(cell.col - otherCell.col) <= 1;
  };

  TouchHandler.prototype.unclickCell = function(cell) {
    var last;
    last = this.lastClicked();
    if (cell !== this.lastClicked()) {
      return null;
    }
    cell.unSelect();
    return this.removeFromClicked(cell);
  };

  TouchHandler.prototype.onEnter = function(cell) {
    var ref;
    console.log(this.mouseIsDown);
    if (this.mouseIsDown && (this.clicked.length === 0 || this.areAdjacent(cell, this.lastClicked())) && (ref = this.cell, indexOf.call(this.clicked, ref) < 0)) {
      return this.clickCell(cell);
    }
  };

  TouchHandler.prototype.onDown = function(cell) {
    this.mouseIsDown = true;
    return this.clickCell(cell);
  };

  TouchHandler.prototype.onUp = function(cell) {
    this.mouseIsDown = false;
    return this.checkSolution();
  };

  TouchHandler.prototype.bindClick = function(obj, func) {
    return $(obj).tap(func);
  };

  TouchHandler.prototype.bindEnter = function(obj, func) {
    return $(obj).vmouseover(func);
  };

  TouchHandler.prototype.bindMousedown = function(obj, func) {
    return $(obj).vmousedown(func);
  };

  TouchHandler.prototype.bindMouseup = function(obj, func) {
    return $(obj).vmouseup(func);
  };

  return TouchHandler;

})();

module.exports = TouchHandler;
