// Generated by CoffeeScript 1.9.3
var TrackingService;

TrackingService = (function() {
  function TrackingService() {}

  TrackingService.boardEvent = function(label) {
    if (label != null) {
      return ga('send', 'event', 'board', label);
    } else {
      return ga('send', 'event', 'board');
    }
  };

  TrackingService.mobileView = function() {
    return this.pageview('Mobile');
  };

  TrackingService.desktopView = function() {
    return this.pageview('Desktop');
  };

  TrackingService.pageview = function(label) {
    if (label != null) {
      return ga('send', 'pageview', label);
    } else {
      return ga('send', 'pageview');
    }
  };

  return TrackingService;

})();

module.exports = TrackingService;
