// Generated by CoffeeScript 1.9.3
var DFS, GameGrid, InputSolver, LastInColumn, seed, testGrid;

DFS = require("./app/services/DFS");

GameGrid = require("./app/models/GameGrid");

InputSolver = require("./app/services/InputSolver");

LastInColumn = require("./app/services/LastInColumn");

this.grid = new GameGrid(3);

testGrid = new DFS(this.grid);

seed = {
  x: 1,
  y: 1
};

testGrid.search(seed, "1+2");

console.log(this.grid.grid[0]);

console.log(this.grid.grid[1]);

console.log(this.grid.grid[2]);

testGrid.search(seed, "3-4");

console.log(this.grid.grid[0]);

console.log(this.grid.grid[1]);

console.log(this.grid.grid[2]);
