// Generated by CoffeeScript 1.9.3
module.exports = {
  mochaEnv: {},
  mochaOptions: {
    colors: true,
    compilers: 'coffee:coffee-script/register',
    reporter: 'dot'
  },
  testFilePattern: '**/*Test.{coffee,js}',
  testHelpers: ['tests/mycha-test-helper.coffee']
};
