// Generated by CoffeeScript 1.9.3
var InputSolver, assert;

InputSolver = require('../app/InputSolver');

assert = require('assert');

describe('InputSolver', function() {
  return describe('#isOperator()', function() {
    it('should return true when value is operator', function() {
      assert.equal(true, InputSolver.isOperator('+'));
      assert.equal(true, InputSolver.isOperator('-'));
      return assert.equal(true, InputSolver.isOperator('*'));
    });
    it('should return false when value is not an operator', function() {
      assert.equal(false, InputSolver.isOperator('1'));
      return assert.equal(false, InputSolver.isOperator('2'));
    });
    return it('should return false when input is empty', function() {
      return assert.equal(false, InputSolver.isOperator(''));
    });
  });
});
