// Generated by CoffeeScript 1.9.3
(function() {
  var GameGrid;

  GameGrid = (function() {
    function GameGrid(size) {
      var grid, i, j, ref;
      grid = [];
      for (i = j = 0, ref = size; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        grid.push([]);
      }
    }

    return GameGrid;

  })();

  module.exports = GameGrid;

}).call(this);
