// Generated by CoffeeScript 1.9.3
var AdjacentIndicies, GameGrid, RandomizedQueuedDFS;

GameGrid = require("./GameGrid");

AdjacentIndicies = require("./AdjacentIndicies");

RandomizedQueuedDFS = (function() {
  function RandomizedQueuedDFS() {}

  RandomizedQueuedDFS.getInitialSeed = function(grid) {
    var i, j, len, x, y;
    for (j = 0, len = grid.length; j < len; j++) {
      i = grid[j];
      x = Math.floor(Math.random() * grid.length) + 1;
      y = Math.floor(Math.random() * grid.length) + 1;
      if (grid[y][x] !== null) {
        return [y, x];
      }
    }
    return false;
  };

  RandomizedQueuedDFS.shuffle = function(array) {
    var i, m, t;
    m = array.length;
    t = void 0;
    i = void 0;
    while (m) {
      i = Math.floor(Math.random() * m--);
      t = array[m];
      array[m] = array[i];
      array[i] = t;
    }
    return array;
  };

  RandomizedQueuedDFS.DFS = function(input, grid, x, y, isFirst) {
    var initialSeed;
    if (input.length === 0) {
      return grid;
    }
    if (isFirst) {
      initialSeed = this.getInitialSeed;
      if (initialSeed === false) {
        return false;
      }
      grid[initialSeed.y][initialSeed.x] = input.charAt(0);
      this.DFS(input.substr(1), grid, initialSeed.x, initialSeed.y(false));
      return this.shuffle(AdjacentIndicies.adjacentIndicies(x, y));
    }
  };

  return RandomizedQueuedDFS;

})();

module.exports = RandomizedQueuedDFS;
