// Generated by CoffeeScript 1.9.3
var GameGrid, InputSolver, MathSwipeController;

InputSolver = require('../services/InputSolver');

GameGrid = require('../models/GameGrid');

MathSwipeController = (function() {
  function MathSwipeController() {
    var board, boardX, boardY, cell, change, gridModel, gridView, i, j, k, l, len, len1, m, n, offset, rect, ref, ref1, row, size, startX, startY, two, width;
    console.log(InputSolver.compute("1+2*-3"));
    gridModel = new GameGrid(3);
    two = new Two({
      fullscreen: true,
      autostart: true
    }).appendTo(document.body);
    size = two.height * .80;
    offset = size * .025;
    width = (size - offset) / gridModel.dimension - offset;
    boardX = two.width / 2;
    boardY = two.height / 2;
    boardY = boardY < size / 2 ? size / 2 : boardY;
    board = two.makeRectangle(boardX, boardY, size, size);
    board.fill = '#F0F8FF';
    startX = boardX - (size + width) / 2;
    startY = boardY - (size + width) / 2;
    change = offset + width;
    gridView = [];
    for (i = k = 1, ref = gridModel.dimension; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      gridView.push([]);
      for (j = l = 1, ref1 = gridModel.dimension; 1 <= ref1 ? l <= ref1 : l >= ref1; j = 1 <= ref1 ? ++l : --l) {
        rect = two.makeRectangle(startX + j * change, startY + i * change, width, width);
        gridView.push(rect);
      }
    }
    for (m = 0, len = gridView.length; m < len; m++) {
      row = gridView[m];
      for (n = 0, len1 = gridView.length; n < len1; n++) {
        cell = gridView[n];
        cell.fill = '#FFEBCD';
      }
    }
  }

  return MathSwipeController;

})();

module.exports = MathSwipeController;
