// Generated by CoffeeScript 1.9.3
var GridCell,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

GridCell = (function() {
  function GridCell() {
    this["delete"] = bind(this["delete"], this);
    this.isEmpty = bind(this.isEmpty, this);
    this.value = ' ';
    this.isClicked = false;
    this.isDeleted = false;
  }

  GridCell.prototype.isEmpty = function() {
    return this.value === ' ';
  };

  GridCell.prototype["delete"] = function() {
    return this.isDeleted = true;
  };

  return GridCell;

})();

module.exports = GridCell;
