// Generated by CoffeeScript 1.9.3
var Tuple,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Tuple = (function() {
  function Tuple(x, y) {
    this.x = x;
    this.y = y;
    this.isElementOf = bind(this.isElementOf, this);
    this.equals = bind(this.equals, this);
  }

  Tuple.prototype.equals = function(otherTuple) {
    if (otherTuple === null) {
      return false;
    }
    return this.x === otherTuple.x && this.y === otherTuple.y;
  };

  Tuple.prototype.isElementOf = function(tuples) {
    var i, len, t;
    for (i = 0, len = tuples.length; i < len; i++) {
      t = tuples[i];
      if (this.equals(t)) {
        return true;
      }
    }
    return false;
  };

  return Tuple;

})();

module.exports = Tuple;
