// Generated by CoffeeScript 1.9.3
var Colors;

Colors = {
  cell: '#EFE8BE',
  cellBorder: '#41565c',
  emptyCell: '#41565c',
  emptyCellBorder: '#41565c',
  board: '#294248',
  select: '#c7a579',
  symbol: 'black',
  deletedGoalGrey: '#2F4F4F'
};

module.exports = Colors;
